version: "3.9"

services:
  mongo:
    image: mongo:5.0
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=<USERNAME>
      - MONGO_INITDB_ROOT_PASSWORD=<PASSWORD>
    volumes:
      - ./data:/data/db
    networks:
      - mongo-network

  mongo-express:
    image: mongo-express:0.54
    container_name: mongo-express
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=<USERNAME>
      - ME_CONFIG_BASICAUTH_PASSWORD=<PASSWORD>
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=<USERNAME>
      - ME_CONFIG_MONGODB_ADMINPASSWORD=<PASSWORD>
    links:
      - mongo
    networks:
      - mongo-network

networks:
  mongo-network:
    driver: bridge